services:
  # Configure the webserver to serve the storybook static site.
  apache:
    image: tugboatqa/httpd:latest
    commands:
      init:
        # Install node.js version 18.
        - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        - apt-get install -y nodejs

        # Set the webroot for Storybook
        - ln -snf "${TUGBOAT_ROOT}/storybook-static" "${DOCROOT}"

        # Add a handy alias if we need to go digging through the filesystem.
        - alias ll="ls -la"

        # Ensure MJS files are properly served and readable by the server.
        - echo "AddType text/javascript .mjs" >> /usr/local/apache2/conf/httpd.conf

      update:
        # Install storybook and other dependencies.
        - npm install

      build:
        # Build the static storybook site.
        - npm run build-storybook
