services:
  # Configure the webserver to serve the storybook static site.
  apache:
    image: tugboatqa/httpd:latest
    commands:
      init:
        # Install node.js version 18.
        - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        - apt-get install -y nodejs

        # Set the webroot for Storybook
        - ln -snf "${TUGBOAT_ROOT}/storybook-static" "${DOCROOT}"
        - alias ll="ls -la"
        - echo "AddType text/javascript .mjs" >> /usr/local/apache2/conf/httpd.conf

      update:
        # Install storybook
        - npm install

      build:
        # Build the static storybook site.
        - npm run build-storybook
